#!/usr/bin/env python3
"""Capture load-bearing scratch at the moment it runs.

Implements part 1 of `docs/PROVENANCE_CONTRACT.md`. Fires on
three events and writes an append-only JSONL log:

  PreToolUse          -> `open` record: the script itself, plus snapshots of
                         any local file about to be shipped to a remote
                         kernel. Written BEFORE the call runs, so it
                         survives the call dying.
  PostToolUse         -> `close` record: output, fidelity, duration.
  PostToolUseFailure  -> `close` record with outcome=failed.

The split is not caution, it is measurement. A failing Bash call delivers
NO `tool_response` to a hook -- its output arrives under `error`, capped at
~10,040 characters, middle elided, with no persisted file to recover from
(see the contract §2, generated by `tools/provenance/run_truncation_probe.py`).
So the one case this exists for -- a scratch script that dies mid-run -- is
exactly the case no post-hoc event can reconstruct. `PreToolUse` is where
the script is available unconditionally, and the script is the asset that
supports promotion to committed code; output can be regenerated once the
generator exists.

**It never blocks. Ever.** Exit 0 unconditionally -- on malformed input, an
unwritable log, a missing directory, a bug in this file. A capture path that
can break a session is worse than no capture path, and one `exit 2` from a
forensic hook would teach exactly the route-around this design exists to
avoid. `capture.sh` wraps it with the same guarantee at the shell layer, so
fail-open holds by two independent layers even if this interpreter cannot
start (the same belt-and-braces reasoning as the c2c-mail hooks next door).

Stdlib only, so it runs under whatever interpreter the harness finds.
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

HOOK_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(HOOK_DIR))

from scratch_predicate import is_scratch  # noqa: E402

# Output larger than this is stored head+tail+digest rather than whole. The
# full bytes stay recoverable from the harness's own persisted file for the
# life of the session; the log's job is to stay readable.
#
# **A policy ceiling, not a measured threshold, and the distinction is the
# point.** Principle 22 governs thresholds that track a measured quantity --
# this is not one. Nothing here scales with n; it is a flat statement that a
# single forensic record should not exceed a couple of megabytes. No
# observation anchors it and none is claimed to.
#
# For context rather than justification: across the local logs to date
# (`tools/provenance/capture_stats.py`), the largest captured output was
# under a kilobyte and nothing has ever been truncated by this ceiling. That
# is descriptive of one machine's logs, which are gitignored and not
# reproducible by anyone else -- so it is deliberately NOT the anchor for
# the value. If this ever needs to become a measured threshold, the
# measurement has to come from committed code regenerating real outputs,
# not from reading the forensic log.
OUTPUT_BLOB_MAX = 2_000_000

# Bumped whenever the record schema or the predicate's rule set changes, so
# a log can be read by a reader that knows which shape to expect.
HOOK_VERSION = "1.1.0"

# Version lookups shell out, so they are cached per session and time-boxed.
# A hook that hangs is a hook that gets removed.
# 5s, not 2: `mighty-colab version` measured ~0.9-1.0s cold on this machine,
# and a timeout set close to the measured cost turns an ordinary slow start
# into a permanently unresolved version field.
VERSION_TIMEOUT_S = 5
_VERSION_COMMANDS = {
    # `version` is a SUBCOMMAND. `mighty-colab --version` is not a valid
    # flag -- it exits non-zero with a usage error, which this probe would
    # have recorded as `probe_failed` forever without ever saying why.
    # Written from the docs and never run until `tests/test_provenance_
    # executor_version.py` ran it; the test exists because a version probe
    # that silently never resolves is worse than no version field, since
    # the record still carries the key.
    "mighty-colab": ["mighty-colab", "version"],
}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def run_dir(payload: dict) -> Path:
    """Run-scoped, in the working tree, gitignored.

    In the tree rather than under ~/.claude so a worktree's captures travel
    with the worktree and die with it.
    """
    root = Path(os.environ.get("BONSAI_PROVENANCE_ROOT")
                or os.environ.get("CLAUDE_PROJECT_DIR")
                or payload.get("cwd") or ".")
    session = str(payload.get("session_id") or "unknown-session")
    return Path(root) / ".provenance" / "runs" / session


def write_blob(directory: Path, data: bytes) -> str:
    """Content-addressed store. Re-running a script costs one copy."""
    digest = hashlib.sha256(data).hexdigest()
    path = directory / "blobs" / digest[:2] / digest[2:]
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    return f"blobs/{digest[:2]}/{digest[2:]}"


def git_state(cwd: str | None) -> dict:
    """Commit, branch and dirtiness at capture time.

    `dirty` is the field that matters: a captured number produced against a
    dirty tree cannot be reproduced from the commit alone, and the record
    should say so rather than implying a clean provenance it never had.
    """
    def _git(*args):
        try:
            out = subprocess.run(["git", *args], cwd=cwd, capture_output=True,
                                 text=True, timeout=VERSION_TIMEOUT_S)
            return out.stdout.strip() if out.returncode == 0 else None
        except Exception:  # noqa: BLE001
            return None

    status = _git("status", "--porcelain")
    return {
        "commit": _git("rev-parse", "HEAD"),
        "branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
        "dirty": bool(status) if status is not None else None,
    }


def executor_version(tool: str, directory: Path) -> dict:
    """Which version of the executing tool ran this, where knowable.

    A capture recording WHAT ran but not WHICH VERSION ran it inherits the
    same skew blindness it exists to close: a number from a different
    mighty-colab or CUDA build is a different number. Cached per run
    directory; absent rather than guessed when it cannot be determined.
    """
    if tool not in _VERSION_COMMANDS:
        return {"tool": tool, "version": None, "resolved_from": "no_probe_known"}
    cache = directory / "executor_versions.json"
    try:
        known = json.loads(cache.read_text()) if cache.exists() else {}
    except Exception:  # noqa: BLE001
        known = {}
    if tool in known:
        return {"tool": tool, "version": known[tool], "resolved_from": "cache"}
    version = None
    try:
        out = subprocess.run(_VERSION_COMMANDS[tool], capture_output=True,
                             text=True, timeout=VERSION_TIMEOUT_S)
        if out.returncode == 0:
            version = out.stdout.strip().splitlines()[0] if out.stdout.strip() else None
    except Exception:  # noqa: BLE001
        version = None
    known[tool] = version
    try:
        cache.parent.mkdir(parents=True, exist_ok=True)
        cache.write_text(json.dumps(known))
    except Exception:  # noqa: BLE001
        pass
    return {"tool": tool, "version": version,
            "resolved_from": "probe" if version else "probe_failed"}


def snapshot_files(paths, directory: Path) -> list[dict]:
    """Copy local files a remote exec is about to read.

    THE case session transcripts provably lose: the transcript keeps the
    path, the kernel receives the bytes, and when the path is a tmp file the
    bytes are gone the moment the session ends.
    """
    out = []
    for raw in paths:
        entry = {"path": str(raw), "existed": False, "sha256": None,
                 "bytes": None, "blob": None}
        try:
            data = Path(raw).read_bytes()
            entry.update(existed=True, bytes=len(data),
                         sha256=hashlib.sha256(data).hexdigest(),
                         blob=write_blob(directory, data))
        except Exception as exc:  # noqa: BLE001
            entry["error"] = f"{type(exc).__name__}: {exc}"
        out.append(entry)
    return out


def extract_output(payload: dict) -> dict:
    """Output plus an honest fidelity flag.

    Fidelity is decided by measurement, not hope. An auditor reading
    `elided` knows the record is partial; one reading a log that silently
    dropped 970,000 characters does not.
    """
    response = payload.get("tool_response")
    if isinstance(response, dict):
        persisted = response.get("persistedOutputPath")
        declared = response.get("persistedOutputSize")
        if persisted:
            try:
                data = Path(persisted).read_bytes()
                complete = declared is None or len(data) == declared
                return {"data": data, "source": "persisted",
                        "fidelity": "complete" if complete else "capped",
                        "declared_size": declared}
            except Exception as exc:  # noqa: BLE001
                return {"data": b"", "source": "persisted_unreadable",
                        "fidelity": "lost", "error": str(exc)}
        text = response.get("stdout") or ""
        # stderr is folded into stdout by the Bash tool (measured), so a
        # non-empty stderr key is unusual enough to keep rather than assume.
        stderr = response.get("stderr") or ""
        combined = (text + stderr).encode()
        return {"data": combined, "source": "inline", "fidelity": "complete"}

    error = payload.get("error")
    if isinstance(error, str):
        # The failure path: capped and middle-elided, with nothing persisted.
        return {"data": error.encode(), "source": "error_field",
                "fidelity": "elided"}
    return {"data": b"", "source": "absent", "fidelity": "lost"}


def append(directory: Path, record: dict) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    with (directory / "capture.jsonl").open("a") as fh:
        fh.write(json.dumps(record) + "\n")


def session_open_record(payload: dict) -> dict:
    """The commit point for a session's capture log.

    Written at `SessionStart`, before any tool call. Its purpose is to make
    ABSENCE diagnostic instead of ambiguous, which is the defect the rest of
    this hook could not fix on its own: with only per-call records, an empty
    log has two readings -- "nothing was scratch" and "the hooks were never
    loaded" -- and no way to tell them apart. Hook registrations are read at
    session start, so the second reading is real and silent.

    With a marker, the question "was this session captured?" is answerable
    from data. Its presence means capture was live; its absence is positive
    evidence the hooks were not loaded. Every later record in the directory
    is then anchored to a session known to have been capturing, so a scratch
    command with no record becomes a real inference about the predicate
    rather than a hope.

    The design is `stage2b-lead`'s, and it is the same move as the manifest
    in their transport layer: a payload with no manifest is UNCOMMITTED, not
    "probably fine." The sidecar exists so that absence means something
    definite.

    Recording the commit HERE as well as per-call also makes a mid-session
    merge visible in the data -- which is precisely the event that produced
    the silent gap in the first place.
    """
    return {
        "capture_id": f"{datetime.now(timezone.utc):%Y%m%dT%H%M%SZ}-session",
        "phase": "session_open",
        "session_id": payload.get("session_id"),
        "ts_utc": _now(),
        "cwd": payload.get("cwd"),
        "source": payload.get("source"),  # startup | resume | clear | compact
        "git": git_state(payload.get("cwd")),
        "hook_version": HOOK_VERSION,
    }


def handle(payload: dict) -> dict | None:
    """Build the record for one event, or None if this call isn't scratch."""
    if (payload.get("hook_event_name") or "") == "SessionStart":
        directory = run_dir(payload)
        record = session_open_record(payload)
        append(directory, record)
        return record

    tool_name = payload.get("tool_name") or ""
    tool_input = payload.get("tool_input") or {}
    verdict = is_scratch(tool_name, tool_input)
    if not verdict.capture:
        return None

    event = payload.get("hook_event_name") or ""
    directory = run_dir(payload)
    tool_use_id = payload.get("tool_use_id")
    base = {
        "capture_id": f"{datetime.now(timezone.utc):%Y%m%dT%H%M%SZ}-"
                      f"{hashlib.sha256(str(tool_use_id).encode()).hexdigest()[:6]}",
        "tool_use_id": tool_use_id,
        "session_id": payload.get("session_id"),
        "ts_utc": _now(),
    }

    if event == "PreToolUse":
        script_text = verdict.script_text
        record = {
            **base, "phase": "open",
            "cwd": payload.get("cwd"),
            "git": git_state(payload.get("cwd")),
            "tool_name": tool_name,
            "trigger_reason": verdict.reason,
            "command": tool_input.get("command"),
            "executor": executor_version(
                "mighty-colab" if "colab" in (tool_input.get("command") or "")
                or "colab" in tool_name else tool_name, directory),
            "script": {
                "text": script_text,
                "source": verdict.script_source,
                "sha256": (hashlib.sha256(script_text.encode()).hexdigest()
                           if script_text else None),
            },
            "referenced_files": snapshot_files(verdict.referenced_files, directory),
        }
        append(directory, record)
        return record

    if event in ("PostToolUse", "PostToolUseFailure"):
        out = extract_output(payload)
        data = out["data"]
        fidelity = out["fidelity"]
        if len(data) > OUTPUT_BLOB_MAX:
            half = OUTPUT_BLOB_MAX // 2
            data = data[:half] + b"\n...[capture truncated]...\n" + data[-half:]
            fidelity = "truncated_by_capture"
        record = {
            **base, "phase": "close",
            "outcome": "failed" if event == "PostToolUseFailure" else "ok",
            "duration_ms": payload.get("duration_ms"),
            "output": {
                "blob": write_blob(directory, data) if data else None,
                "bytes": len(out["data"]),
                "source": out["source"],
                "fidelity": fidelity,
            },
        }
        append(directory, record)
        return record
    return None


def main() -> int:
    try:
        payload = json.loads(sys.stdin.read())
        handle(payload)
    except Exception:  # noqa: BLE001
        # Deliberately silent and deliberately total. See the module
        # docstring: this hook may never block, and a capture failure must
        # cost a missing record, never a broken session.
        pass
    try:
        print(json.dumps({"suppressOutput": True}))
    except Exception:  # noqa: BLE001
        pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
